import {
  Share2,
  Megaphone,
  Palette,
  Code,
  Video,
  Camera,
  Search,
  FileText,
  ArrowRight,
  CheckCircle,
  Sparkles,
  TrendingUp,
  BarChart3,
  Target,
  Rocket,
  Mail,
  MessageCircle,
  Globe,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Youtube,
  Monitor,
  Smartphone,
  Layout,
  PenTool,
  Image,
  Film,
  Mic,
  Headphones,
  Edit3,
  Eye,
  Users,
  UserPlus,
  Award,
  Zap,
  Star,
  Heart,
  ShoppingCart,
  DollarSign,
  CreditCard,
  Gift,
  Tag,
  Percent,
  Bell,
  BellRing,
  Send,
  Inbox,
  AtSign,
  Hash,
  MousePointer,
  MousePointerClick,
  Lightbulb,
  Briefcase,
  PieChart,
  Activity,
  Layers,
  Package,
  Settings,
  Cpu,
  Wifi,
  Radio,
  Tv,
  Cast,
  Volume2,
  PlayCircle,
  Calendar,
  Clock,
  MapPin,
  Flag,
  Bookmark,
  ThumbsUp,
  MessageSquare,
  Share,
  Repeat,
  Download,
  Upload,
  Link,
  ExternalLink,
  Maximize,
  RefreshCw,
} from "lucide-react";

export const MARKETING_ICONS = [
  { name: "Megaphone", icon: Megaphone, category: "Advertising" },
  { name: "TrendingUp", icon: TrendingUp, category: "Analytics" },
  { name: "Target", icon: Target, category: "Strategy" },
  { name: "Share2", icon: Share2, category: "Social" },
  { name: "Palette", icon: Palette, category: "Design" },
  { name: "Code", icon: Code, category: "Development" },
  { name: "Video", icon: Video, category: "Content" },
  { name: "Camera", icon: Camera, category: "Photography" },
  { name: "Search", icon: Search, category: "SEO" },
  { name: "FileText", icon: FileText, category: "Content" },
  { name: "CheckCircle", icon: CheckCircle, category: "Success" },
  { name: "Sparkles", icon: Sparkles, category: "Creative" },
  { name: "BarChart3", icon: BarChart3, category: "Analytics" },
  { name: "Rocket", icon: Rocket, category: "Growth" },
  { name: "Mail", icon: Mail, category: "Email" },
  { name: "MessageCircle", icon: MessageCircle, category: "Chat" },
  { name: "Globe", icon: Globe, category: "Web" },
  { name: "Instagram", icon: Instagram, category: "Social" },
  { name: "Facebook", icon: Facebook, category: "Social" },
  { name: "Twitter", icon: Twitter, category: "Social" },
  { name: "Linkedin", icon: Linkedin, category: "Social" },
  { name: "Youtube", icon: Youtube, category: "Video" },
  { name: "Monitor", icon: Monitor, category: "Digital" },
  { name: "Smartphone", icon: Smartphone, category: "Mobile" },
  { name: "Layout", icon: Layout, category: "Design" },
  { name: "PenTool", icon: PenTool, category: "Design" },
  { name: "Image", icon: Image, category: "Media" },
  { name: "Film", icon: Film, category: "Video" },
  { name: "Mic", icon: Mic, category: "Audio" },
  { name: "Headphones", icon: Headphones, category: "Audio" },
  { name: "Edit3", icon: Edit3, category: "Editing" },
  { name: "Eye", icon: Eye, category: "Views" },
  { name: "Users", icon: Users, category: "Audience" },
  { name: "UserPlus", icon: UserPlus, category: "Growth" },
  { name: "Award", icon: Award, category: "Success" },
  { name: "Zap", icon: Zap, category: "Fast" },
  { name: "Star", icon: Star, category: "Featured" },
  { name: "Heart", icon: Heart, category: "Engagement" },
  { name: "ShoppingCart", icon: ShoppingCart, category: "Ecommerce" },
  { name: "DollarSign", icon: DollarSign, category: "Finance" },
  { name: "CreditCard", icon: CreditCard, category: "Payment" },
  { name: "Gift", icon: Gift, category: "Offers" },
  { name: "Tag", icon: Tag, category: "Pricing" },
  { name: "Percent", icon: Percent, category: "Discount" },
  { name: "Bell", icon: Bell, category: "Notifications" },
  { name: "BellRing", icon: BellRing, category: "Alerts" },
  { name: "Send", icon: Send, category: "Send" },
  { name: "Inbox", icon: Inbox, category: "Messages" },
  { name: "AtSign", icon: AtSign, category: "Mentions" },
  { name: "Hash", icon: Hash, category: "Hashtags" },
  { name: "MousePointer", icon: MousePointer, category: "Click" },
  { name: "MousePointerClick", icon: MousePointerClick, category: "CTA" },
  { name: "Lightbulb", icon: Lightbulb, category: "Ideas" },
  { name: "Briefcase", icon: Briefcase, category: "Business" },
  { name: "PieChart", icon: PieChart, category: "Data" },
  { name: "Activity", icon: Activity, category: "Performance" },
  { name: "Layers", icon: Layers, category: "Multiple" },
  { name: "Package", icon: Package, category: "Product" },
  { name: "Settings", icon: Settings, category: "Config" },
  { name: "Cpu", icon: Cpu, category: "Tech" },
  { name: "Wifi", icon: Wifi, category: "Online" },
  { name: "Radio", icon: Radio, category: "Broadcast" },
  { name: "Tv", icon: Tv, category: "Media" },
  { name: "Cast", icon: Cast, category: "Stream" },
  { name: "Volume2", icon: Volume2, category: "Audio" },
  { name: "PlayCircle", icon: PlayCircle, category: "Play" },
  { name: "Calendar", icon: Calendar, category: "Schedule" },
  { name: "Clock", icon: Clock, category: "Time" },
  { name: "MapPin", icon: MapPin, category: "Location" },
  { name: "Flag", icon: Flag, category: "Campaign" },
  { name: "Bookmark", icon: Bookmark, category: "Save" },
  { name: "ThumbsUp", icon: ThumbsUp, category: "Like" },
  { name: "MessageSquare", icon: MessageSquare, category: "Comments" },
  { name: "Share", icon: Share, category: "Share" },
  { name: "Repeat", icon: Repeat, category: "Repost" },
  { name: "Download", icon: Download, category: "Download" },
  { name: "Upload", icon: Upload, category: "Upload" },
  { name: "Link", icon: Link, category: "Links" },
  { name: "ExternalLink", icon: ExternalLink, category: "External" },
  { name: "Maximize", icon: Maximize, category: "Expand" },
  { name: "RefreshCw", icon: RefreshCw, category: "Refresh" },
  { name: "ArrowRight", icon: ArrowRight, category: "Next" },
];

// Function to get icon component by name
export const getIconByName = (iconName) => {
  const iconData = MARKETING_ICONS.find((i) => i.name === iconName);
  return iconData?.icon || null;
};
