import {
  Share2,
  Megaphone,
  Palette,
  Code,
  Video,
  Camera,
  Search,
  FileText,
  ArrowRight,
  CheckCircle,
  Sparkles,
  TrendingUp,
  BarChart3,
  Target,
  Rocket,
  Mail,
  MessageCircle,
  Globe,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Youtube,
  Monitor,
  Smartphone,
  Layout,
  PenTool,
  Image,
  Film,
  Mic,
  Headphones,
  Edit3,
  Eye,
  Users,
  UserPlus,
  Award,
  Zap,
  Star,
  Heart,
  ShoppingCart,
  DollarSign,
  CreditCard,
  Gift,
  Tag,
  Percent,
  Bell,
  BellRing,
  Send,
  Inbox,
  AtSign,
  Hash,
  MousePointer,
  MousePointerClick,
  Lightbulb,
  Briefcase,
  PieChart,
  Activity,
  Layers,
  Package,
  Settings,
  Cpu,
  Wifi,
  Radio,
  Tv,
  Cast,
  Volume2,
  PlayCircle,
  Calendar,
  Clock,
  MapPin,
  Flag,
  Bookmark,
  ThumbsUp,
  MessageSquare,
  Share,
  Repeat,
  Download,
  Upload,
  Link,
  ExternalLink,
  Maximize,
  RefreshCw,
  Crown,
  Flame,
  TrendingDown,
  ArrowUp,
  ArrowDown,
  CircleDollarSign,
  Wallet,
  Building,
  Building2,
  Store,
  ShoppingBag,
  Receipt,
  Banknote,
  LineChart,
  BarChart,
  BarChart2,
  BarChart4,
  Database,
  Server,
  HardDrive,
  Cloud,
  CloudDownload,
  CloudUpload,
  FolderOpen,
  File,
  Files,
  Folder,
  FileEdit,
  FileCheck,
  FilePlus,
  UserCheck,
  UserMinus,
  UserX,
  UserCog,
  UsersRound,
  BadgeCheck,
  BadgeAlert,
  Shield,
  ShieldCheck,
  Lock,
  Unlock,
  Key,
  QrCode,
  Workflow,
  GitBranch,
  Boxes,
  Box,
  Archive,
  Truck,
  Home,
  GraduationCap,
  BookOpen,
  Book,
  FileSpreadsheet,
  Presentation,
  Trophy,
  Medal,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Wrench,
  Paintbrush,
  Copy,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Filter,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  Power,
  Battery,
  BatteryCharging,
  Signal,
  Rss,
  Podcast,
  Music,
  Disc,
  AlarmClock,
  Timer,
  Hourglass,
  Watch,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Droplet,
  Compass,
  Navigation,
  Map,
  MapPinned,
  Mountain,
  Flower,
  Sprout,
  Coffee,
  Dumbbell,
  HeartPulse,
  Smile,
  Diamond,
  Coins,
  Laptop,
} from "lucide-react";

export const MARKETING_ICONS = [
  // Core Marketing
  { name: "Megaphone", icon: Megaphone, category: "Marketing" },
  { name: "TrendingUp", icon: TrendingUp, category: "Growth" },
  { name: "TrendingDown", icon: TrendingDown, category: "Analytics" },
  { name: "Target", icon: Target, category: "Strategy" },
  { name: "Rocket", icon: Rocket, category: "Launch" },
  { name: "Flame", icon: Flame, category: "Trending" },
  { name: "Sparkles", icon: Sparkles, category: "Special" },
  { name: "Crown", icon: Crown, category: "Premium" },
  { name: "Award", icon: Award, category: "Achievement" },
  { name: "Trophy", icon: Trophy, category: "Success" },
  { name: "Medal", icon: Medal, category: "Winner" },
  { name: "Star", icon: Star, category: "Featured" },
  { name: "Diamond", icon: Diamond, category: "Premium" },

  // Social Media
  { name: "Share2", icon: Share2, category: "Social" },
  { name: "Share", icon: Share, category: "Social" },
  { name: "Instagram", icon: Instagram, category: "Social" },
  { name: "Facebook", icon: Facebook, category: "Social" },
  { name: "Twitter", icon: Twitter, category: "Social" },
  { name: "Linkedin", icon: Linkedin, category: "Social" },
  { name: "Youtube", icon: Youtube, category: "Social" },
  { name: "MessageCircle", icon: MessageCircle, category: "Chat" },
  { name: "MessageSquare", icon: MessageSquare, category: "Comments" },
  { name: "ThumbsUp", icon: ThumbsUp, category: "Like" },
  { name: "Heart", icon: Heart, category: "Love" },
  { name: "Repeat", icon: Repeat, category: "Repost" },
  { name: "AtSign", icon: AtSign, category: "Mention" },
  { name: "Hash", icon: Hash, category: "Hashtag" },

  // Content & Media
  { name: "Video", icon: Video, category: "Video" },
  { name: "Film", icon: Film, category: "Movie" },
  { name: "Camera", icon: Camera, category: "Photo" },
  { name: "Image", icon: Image, category: "Image" },
  { name: "Mic", icon: Mic, category: "Audio" },
  { name: "Headphones", icon: Headphones, category: "Audio" },
  { name: "Music", icon: Music, category: "Music" },
  { name: "Disc", icon: Disc, category: "Media" },
  { name: "Volume2", icon: Volume2, category: "Sound" },
  { name: "PlayCircle", icon: PlayCircle, category: "Play" },
  { name: "Podcast", icon: Podcast, category: "Podcast" },
  { name: "Radio", icon: Radio, category: "Broadcast" },
  { name: "Tv", icon: Tv, category: "Television" },
  { name: "Cast", icon: Cast, category: "Stream" },

  // Design & Creative
  { name: "Palette", icon: Palette, category: "Design" },
  { name: "PenTool", icon: PenTool, category: "Design" },
  { name: "Paintbrush", icon: Paintbrush, category: "Art" },
  { name: "Layout", icon: Layout, category: "Layout" },
  { name: "Edit3", icon: Edit3, category: "Edit" },
  { name: "Lightbulb", icon: Lightbulb, category: "Idea" },

  // Analytics & Data
  { name: "BarChart3", icon: BarChart3, category: "Analytics" },
  { name: "BarChart", icon: BarChart, category: "Chart" },
  { name: "BarChart2", icon: BarChart2, category: "Chart" },
  { name: "BarChart4", icon: BarChart4, category: "Chart" },
  { name: "LineChart", icon: LineChart, category: "Analytics" },
  { name: "PieChart", icon: PieChart, category: "Data" },
  { name: "Activity", icon: Activity, category: "Activity" },
  { name: "Eye", icon: Eye, category: "Views" },
  { name: "FileSpreadsheet", icon: FileSpreadsheet, category: "Data" },
  { name: "Presentation", icon: Presentation, category: "Present" },

  // E-commerce & Sales
  { name: "ShoppingCart", icon: ShoppingCart, category: "Shop" },
  { name: "ShoppingBag", icon: ShoppingBag, category: "Shopping" },
  { name: "Store", icon: Store, category: "Store" },
  { name: "DollarSign", icon: DollarSign, category: "Money" },
  { name: "CircleDollarSign", icon: CircleDollarSign, category: "Finance" },
  { name: "CreditCard", icon: CreditCard, category: "Payment" },
  { name: "Wallet", icon: Wallet, category: "Wallet" },
  { name: "Receipt", icon: Receipt, category: "Receipt" },
  { name: "Banknote", icon: Banknote, category: "Cash" },
  { name: "Coins", icon: Coins, category: "Money" },
  { name: "Gift", icon: Gift, category: "Gift" },
  { name: "Tag", icon: Tag, category: "Price" },
  { name: "Percent", icon: Percent, category: "Discount" },
  { name: "Package", icon: Package, category: "Product" },
  { name: "Box", icon: Box, category: "Package" },
  { name: "Boxes", icon: Boxes, category: "Inventory" },
  { name: "Archive", icon: Archive, category: "Storage" },
  { name: "Truck", icon: Truck, category: "Delivery" },

  // Communication
  { name: "Mail", icon: Mail, category: "Email" },
  { name: "Send", icon: Send, category: "Send" },
  { name: "Inbox", icon: Inbox, category: "Inbox" },
  { name: "Bell", icon: Bell, category: "Notification" },
  { name: "BellRing", icon: BellRing, category: "Alert" },

  // Web & Digital
  { name: "Globe", icon: Globe, category: "Web" },
  { name: "Laptop", icon: Laptop, category: "Device" },
  { name: "Monitor", icon: Monitor, category: "Desktop" },
  { name: "Smartphone", icon: Smartphone, category: "Mobile" },
  { name: "Code", icon: Code, category: "Code" },
  { name: "Search", icon: Search, category: "Search" },
  { name: "Link", icon: Link, category: "Link" },
  { name: "ExternalLink", icon: ExternalLink, category: "External" },
  { name: "Download", icon: Download, category: "Download" },
  { name: "Upload", icon: Upload, category: "Upload" },
  { name: "Cloud", icon: Cloud, category: "Cloud" },
  { name: "CloudDownload", icon: CloudDownload, category: "Download" },
  { name: "CloudUpload", icon: CloudUpload, category: "Upload" },
  { name: "Server", icon: Server, category: "Server" },
  { name: "Database", icon: Database, category: "Database" },
  { name: "HardDrive", icon: HardDrive, category: "Storage" },
  { name: "Wifi", icon: Wifi, category: "Network" },
  { name: "Signal", icon: Signal, category: "Signal" },
  { name: "Rss", icon: Rss, category: "Feed" },

  // Users & Team
  { name: "Users", icon: Users, category: "Users" },
  { name: "UsersRound", icon: UsersRound, category: "Team" },
  { name: "UserPlus", icon: UserPlus, category: "Add User" },
  { name: "UserCheck", icon: UserCheck, category: "Verified" },
  { name: "UserMinus", icon: UserMinus, category: "Remove" },
  { name: "UserX", icon: UserX, category: "Block" },
  { name: "UserCog", icon: UserCog, category: "Settings" },

  // Business & Office
  { name: "Briefcase", icon: Briefcase, category: "Business" },
  { name: "Building", icon: Building, category: "Office" },
  { name: "Building2", icon: Building2, category: "Company" },
  { name: "Home", icon: Home, category: "Home" },
  { name: "GraduationCap", icon: GraduationCap, category: "Education" },

  // Files & Documents
  { name: "FileText", icon: FileText, category: "Document" },
  { name: "File", icon: File, category: "File" },
  { name: "Files", icon: Files, category: "Files" },
  { name: "Folder", icon: Folder, category: "Folder" },
  { name: "FolderOpen", icon: FolderOpen, category: "Open" },
  { name: "FileEdit", icon: FileEdit, category: "Edit" },
  { name: "FileCheck", icon: FileCheck, category: "Approved" },
  { name: "FilePlus", icon: FilePlus, category: "New File" },
  { name: "BookOpen", icon: BookOpen, category: "Book" },
  { name: "Book", icon: Book, category: "Library" },
  { name: "Clipboard", icon: Clipboard, category: "Clipboard" },
  { name: "ClipboardCheck", icon: ClipboardCheck, category: "Done" },
  { name: "ClipboardList", icon: ClipboardList, category: "List" },
  { name: "Copy", icon: Copy, category: "Copy" },

  // Actions & Controls
  { name: "CheckCircle", icon: CheckCircle, category: "Success" },
  { name: "BadgeCheck", icon: BadgeCheck, category: "Verified" },
  { name: "Zap", icon: Zap, category: "Fast" },
  { name: "MousePointer", icon: MousePointer, category: "Click" },
  { name: "MousePointerClick", icon: MousePointerClick, category: "Action" },
  { name: "ArrowRight", icon: ArrowRight, category: "Next" },
  { name: "ArrowUp", icon: ArrowUp, category: "Up" },
  { name: "ArrowDown", icon: ArrowDown, category: "Down" },
  { name: "RefreshCw", icon: RefreshCw, category: "Refresh" },
  { name: "Maximize", icon: Maximize, category: "Expand" },
  { name: "Settings", icon: Settings, category: "Settings" },
  { name: "SlidersHorizontal", icon: SlidersHorizontal, category: "Controls" },
  { name: "Filter", icon: Filter, category: "Filter" },
  { name: "ToggleLeft", icon: ToggleLeft, category: "Toggle" },
  { name: "ToggleRight", icon: ToggleRight, category: "Switch" },
  { name: "Power", icon: Power, category: "Power" },

  // Security & Trust
  { name: "Shield", icon: Shield, category: "Security" },
  { name: "ShieldCheck", icon: ShieldCheck, category: "Protected" },
  { name: "Lock", icon: Lock, category: "Secure" },
  { name: "Unlock", icon: Unlock, category: "Open" },
  { name: "Key", icon: Key, category: "Access" },
  { name: "QrCode", icon: QrCode, category: "QR" },
  { name: "BadgeAlert", icon: BadgeAlert, category: "Warning" },

  // Time & Schedule
  { name: "Calendar", icon: Calendar, category: "Calendar" },
  { name: "Clock", icon: Clock, category: "Time" },
  { name: "AlarmClock", icon: AlarmClock, category: "Alarm" },
  { name: "Timer", icon: Timer, category: "Timer" },
  { name: "Hourglass", icon: Hourglass, category: "Wait" },
  { name: "Watch", icon: Watch, category: "Watch" },

  // Location & Navigation
  { name: "MapPin", icon: MapPin, category: "Location" },
  { name: "MapPinned", icon: MapPinned, category: "Pin" },
  { name: "Map", icon: Map, category: "Map" },
  { name: "Navigation", icon: Navigation, category: "Navigate" },
  { name: "Compass", icon: Compass, category: "Direction" },

  // Utilities
  { name: "Flag", icon: Flag, category: "Flag" },
  { name: "Bookmark", icon: Bookmark, category: "Save" },
  { name: "Layers", icon: Layers, category: "Layers" },
  { name: "Cpu", icon: Cpu, category: "Tech" },
  { name: "Workflow", icon: Workflow, category: "Process" },
  { name: "GitBranch", icon: GitBranch, category: "Branch" },
  { name: "Wrench", icon: Wrench, category: "Tools" },

  // Status & Alerts
  { name: "AlertCircle", icon: AlertCircle, category: "Alert" },
  { name: "AlertTriangle", icon: AlertTriangle, category: "Warning" },
  { name: "Info", icon: Info, category: "Info" },
  { name: "HelpCircle", icon: HelpCircle, category: "Help" },
  { name: "Smile", icon: Smile, category: "Happy" },

  // Nature & Lifestyle
  { name: "Sun", icon: Sun, category: "Sun" },
  { name: "Moon", icon: Moon, category: "Moon" },
  { name: "CloudRain", icon: CloudRain, category: "Weather" },
  { name: "Wind", icon: Wind, category: "Wind" },
  { name: "Droplet", icon: Droplet, category: "Water" },
  { name: "Mountain", icon: Mountain, category: "Mountain" },
  { name: "Flower", icon: Flower, category: "Nature" },
  { name: "Sprout", icon: Sprout, category: "Growth" },
  { name: "Coffee", icon: Coffee, category: "Coffee" },
  { name: "Dumbbell", icon: Dumbbell, category: "Fitness" },
  { name: "HeartPulse", icon: HeartPulse, category: "Health" },

  // Power & Energy
  { name: "Battery", icon: Battery, category: "Battery" },
  { name: "BatteryCharging", icon: BatteryCharging, category: "Charging" },
];

// Function to get icon component by name
export const getIconByName = (iconName) => {
  const iconData = MARKETING_ICONS.find((i) => i.name === iconName);
  return iconData?.icon || Sparkles;
};

// Function to get icons by category
export const getIconsByCategory = (category) => {
  return MARKETING_ICONS.filter((icon) =>
    icon.category.toLowerCase().includes(category.toLowerCase()),
  );
};

// Function to search icons
export const searchIcons = (query) => {
  const lowerQuery = query.toLowerCase();
  return MARKETING_ICONS.filter(
    (icon) =>
      icon.name.toLowerCase().includes(lowerQuery) ||
      icon.category.toLowerCase().includes(lowerQuery),
  );
};

// Get all unique categories
export const getAllCategories = () => {
  const categories = [...new Set(MARKETING_ICONS.map((icon) => icon.category))];
  return categories.sort();
};
